### ISSUE TITLE
Hyper Fails to start pod

### ISSUE THREAD

**Issue by bketelsen** [hyperhq/hyper#1]
Ubuntu 15.04
docker 1.6

[HYPER INFO  0528 23:53:05 04155 hyperd.go] The config file is /etc/hyper/config
[HYPER INFO  0528 23:53:05 04155 daemon.go] The config: kernel=/var/lib/hyper/kernel, initrd=/var/lib/hyper/hyper-initrd.img
[HYPER INFO  0528 23:53:05 04155 daemon.go] The config: bridge=, ip=
[HYPER INFO  0528 23:53:05 04155 daemon.go] The config: bios=/var/lib/hyper/bios-qboot.bin, cbfs=/var/lib/hyper/cbfs-qboot.rom
[HYPER INFO  0528 23:53:05 04155 hyperd.go] Hyper daemon: 0.1 0
[HYPER INFO  0528 23:53:05 04155 job.go] +job acceptconnections()
[HYPER INFO  0528 23:53:05 04155 job.go] -job acceptconnections() OK
[HYPER INFO  0528 23:53:05 04155 hyperd.go] Daemon has completed initialization
[HYPER INFO  0528 23:53:05 04155 job.go] +job serveapi(unix:///var/run/hyper.sock)
[HYPER INFO  0528 23:53:05 04155 server.go] Listening for HTTP on unix (/var/run/hyper.sock)
[HYPER INFO  0528 23:53:05 04155 server.go] Registering GET, /info
[HYPER INFO  0528 23:53:05 04155 server.go] Registering GET, /pod/info
[HYPER INFO  0528 23:53:05 04155 server.go] Registering GET, /version
[HYPER INFO  0528 23:53:05 04155 server.go] Registering GET, /list
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /image/create
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /pod/remove
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /tty/resize
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /container/create
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /pod/create
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /pod/start
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /pod/run
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /pod/stop
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /vm/create
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /vm/kill
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /exec
[HYPER INFO  0528 23:53:05 04155 server.go] Registering POST, /attach
[HYPER INFO  0528 23:53:05 04155 server.go] Registering OPTIONS, 

[HYPER INFO  0528 23:53:56 04155 server.go] Calling POST /pod/start
[HYPER INFO  0528 23:53:56 04155 job.go] +job podStart(pod-DnZyhANaAx, )
[HYPER INFO  0528 23:53:56 04155 pod.go] pod:%s, vm:%spod-DnZyhANaAx
POD id is pod-DnZyhANaAx
[HYPER INFO  0528 23:53:56 04155 vm_states.go] got spec, prepare devices
[HYPER INFO  0528 23:53:56 04155 qmp_handler.go] got new session during initializing
[HYPER ERROR 0528 23:53:57 04155 init_comm.go] Cannot connect to hyper socket dial unix /var/run/hyper/vm-sbJZGkBVOt/hyper.sock: connection refused
[HYPER ERROR 0528 23:53:57 04155 vm_states.go] Cannot connect to hyper socket dial unix /var/run/hyper/vm-sbJZGkBVOt/hyper.sock: connection refused
[HYPER ERROR 0528 23:53:57 04155 vm_states.go] Shutting down because of an exception: Fail during init pod running environment
[HYPER ERROR 0528 23:53:57 04155 tty.go] Cannot connect to tty socket dial unix /var/run/hyper/vm-sbJZGkBVOt/tty.sock: connection refused
[HYPER ERROR 0528 23:53:57 04155 qmp_handler.go] failed to connected to /var/run/hyper/vm-sbJZGkBVOt/qmp.sock dial unix /var/run/hyper/vm-sbJZGkBVOt/qmp.sock: connection refused
[HYPER ERROR 0528 23:53:57 04155 qemu_process.go] failed to connected to /var/run/hyper/vm-sbJZGkBVOt/console.sock dial unix /var/run/hyper/vm-sbJZGkBVOt/console.sock: no such file or directory
[HYPER ERROR 0528 23:53:57 04155 qmp_handler.go] QMP initialize failed
[HYPER WARN  0528 23:54:07 04155 vm_states.go] Qemu did not exit in time, try to stop it
[HYPER ERROR 0528 23:54:07 04155 vm_states.go] Shutting down because of an exception: vm terminating timeout
[HYPER INFO  0528 23:54:17 04155 qemu_process.go] kill Qemu... 4398
[HYPER INFO  0528 23:54:17 04155 vm_states.go] Got Qemu force killed message, go to cleaning up
[HYPER ERROR 0528 23:54:17 04155 pod.go] QEMU response data is nil
[HYPER INFO  0528 23:54:17 04155 job.go] -job podStart(pod-DnZyhANaAx, ) ERR: QEMU response data is nil
[HYPER ERROR 0528 23:54:17 04155 server.go] Handler for POST /pod/start returned error: QEMU response data is nil
[HYPER ERROR 0528 23:54:17 04155 server.go] HTTP Error: statusCode=500 QEMU response data is nil
[HYPER INFO  0528 23:55:17 04155 vm_states.go] Device removing timeout

**Comment by gnawux** [comment]
Hi, bketelsen

Could you stop the daemon and re-install hyper. Sorry for the inconvenience, there is one broken installation pack in the past hour, a qboot bios with a wrong filename in it.

Thank you!

**Comment by gnawux** [comment]
The direct download link has been put on readme: https://hyper-install.s3.amazonaws.com/hyper-latest.tgz

Cheers

**Comment by bketelsen** [comment]
That solved the problem, thank you.
