### ISSUE TITLE
Able to isolate networks?

### ISSUE THREAD

**Issue by charliedrage** [hyperhq/hyper#10]
Is there a way to isolate what networks QEMU uses on the host?

For example, specifying in the podfile to use vnet0 or vnet1, etc, similar to how libvirt does it with the xml formatting.

If there isn't, I'm willing to contribute in adding the ability to specify a specific public / private IP + network.

Also, wouldn't:

network.go
```go
const (
	defaultBridgeIface	= "hyper0"
	defaultBridgeIP		= "192.168.123.0/24"
)
```
cause the max amount of IP's be 253, only being able to run 253 appcontainers. Shouldn't we make this more dynamic?

**Comment by gnawux** [comment]
hi @charliedrage , the `hyper0` could configure in the [config file](https://docs.hyper.sh/reference/configuration.html),  `/etc/hyper/config` by default, it supports the following config items:

    Bridge = hyper0
    BridgeIP = 192.168.123.1/24

currently, only bridge is supported, more networking features in the future.

**Comment by charliedrage** [comment]
@gnawux awesome. looking forward to the new network features, hopefully there's the ability to specify a network interface / ip address in the future.
