### ISSUE TITLE
Can not start on CentOS 7

### ISSUE THREAD

**Issue by CMGS** [hyperhq/hyper#115]
After server hyperd start, we got those logs

```
[root@lothar ~]# hyperd --nondaemon
[HYPER INFO  1023 14:27:55 32221 docker.go] success to create docker
[HYPER INFO  1023 14:27:55 32221 daemon.go] The config: kernel=/var/lib/hyper/kernel, initrd=/var/lib/hyper/hyper-initrd.img
[HYPER INFO  1023 14:27:55 32221 daemon.go] The config: vbox image=
[HYPER INFO  1023 14:27:55 32221 daemon.go] The config: bridge=, ip=
[HYPER INFO  1023 14:27:55 32221 daemon.go] The config: bios=/var/lib/hyper/bios-qboot.bin, cbfs=/var/lib/hyper/cbfs-qboot.rom
[HYPER ERROR 1023 14:27:55 32221 driver_linux.go] 58465342
[HYPER INFO  1023 14:27:55 32221 driver.go] [graphdriver] using prior storage driver "devicemapper"
[HYPER INFO  1023 14:27:55 32221 daemon.go] Creating images graph
[HYPER INFO  1023 14:27:55 32221 daemon.go] Creating repository list
[HYPER INFO  1023 14:27:55 32221 daemon.go] Loading containers: done.
[HYPER INFO  1023 14:27:55 32221 docker.go] Daemon has completed initialization
[HYPER INFO  1023 14:27:55 32221 xen.go] failed to initialize xen context
[HYPER WARN  1023 14:27:55 32221 hyperd.go] Driver xen is unavailable

Qemu Driver Loaded
[HYPER INFO  1023 14:27:55 32221 hyperd.go] The hypervisor's driver is kvm
[HYPER ERROR 1023 14:27:55 32221 hyperd.go] InitNetwork failed, Unable to setup goto HYPER rule iptables failed: iptables --wait -t nat -I OUTPUT -m addrtype --dst-type LOCAL ! -d 127.0.0.1/8 -j HYPER: iptables: No chain/target/match by that name.
 (exit status 1)
[root@lothar ~]# iptables --wait -t nat -I OUTPUT -m addrtype --dst-type LOCAL ! -d 127.0.0.1/8 -j HYPER
iptables: No chain/target/match by that name.
```

**Comment by carmark** [comment]
@CMGS 

How do you get the `hyperd` binary, build it from source code?

**Comment by CMGS** [comment]
@carmark 

got by ```curl -sSL https://hyper.sh/install | bash``` 

iptables was replaced by FirewallD in CentOS 7, so i think it cause this problem

**Comment by gao-feng** [comment]
@CMGS Can you show me the output of `iptables -t nat -nvL |grep Chain`, and check if `xt_addrtype` kernel module is available on your centos?

**Comment by CMGS** [comment]
[root@lothar ~]# iptables -t nat -nvL |grep Chain
Chain PREROUTING (policy ACCEPT 1944K packets, 1025M bytes)
Chain INPUT (policy ACCEPT 24 packets, 1244 bytes)
Chain OUTPUT (policy ACCEPT 2647 packets, 201K bytes)
Chain POSTROUTING (policy ACCEPT 2647 packets, 201K bytes)
Chain DOCKER (0 references)
Chain HYPER (0 references)
Chain OUTPUT_direct (1 references)
Chain POSTROUTING_ZONES (1 references)
Chain POSTROUTING_ZONES_SOURCE (1 references)
Chain POSTROUTING_direct (1 references)
Chain POST_public (2 references)
Chain POST_public_allow (1 references)
Chain POST_public_deny (1 references)
Chain POST_public_log (1 references)
Chain PREROUTING_ZONES (1 references)
Chain PREROUTING_ZONES_SOURCE (1 references)
Chain PREROUTING_direct (1 references)
Chain PRE_public (2 references)
Chain PRE_public_allow (1 references)
Chain PRE_public_deny (1 references)
Chain PRE_public_log (1 references)

On Thu, Nov 5, 2015 at 4:31 PM, Gao feng <notifications@github.com> wrote:

> @CMGS <https://github.com/CMGS> Can you show me the output of iptables -t
> nat -nvL |grep Chain, and check if xt_addrtype kernel module is available
> on your centos?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyperhq/hyper/issues/115#issuecomment-153987035>.
>



-- 

-CMGS
A simple coder.
Love travel, sports especially outdoor sports and computer technology.
Have a dream that one day can tour around.

**Comment by gnawux** [comment]
There is output chain listed here, and I guess this error might be caused by SELinux. (guess only)

**Comment by gao-feng** [comment]
unavailable `addrtype`  match  will cause this error too

**Comment by gnawux** [comment]
@CMGS 

for centOS user, could you try the binary in this rpm

https://s3.amazonaws.com/hyper-install/hyper-0.4-1.el7.centos.src.rpm

I was working in build hyper native packages in hyper VMs (PR: https://github.com/hyperhq/hyper/pull/135 ), this is the first distro package to build, and I need some tester to try it.

PS: you need remove hyper and hyperd binary in /usr/local/bin, because rpm will put binary in /usr/bin

Thank you.

**Comment by CMGS** [comment]
OK，I will test it ASAP

On Wed, Nov 25, 2015 at 5:41 PM, Xu Wang <notifications@github.com> wrote:

> @CMGS <https://github.com/CMGS>
>
> for centOS user, could you try the binary in this rpm
>
> https://s3.amazonaws.com/hyper-install/hyper-0.4-1.el7.centos.src.rpm
>
> I was working in build hyper native packages in hyper VMs (PR: #135
> <https://github.com/hyperhq/hyper/pull/135> ), this is the first distro
> package to build, and I need some tester to try it.
>
> PS: you need remove hyper and hyperd binary in /usr/local/bin, because rpm
> will put binary in /usr/bin
>
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyperhq/hyper/issues/115#issuecomment-159551285>.
>



-- 

-CMGS
A simple coder.
Love travel, sports especially outdoor sports and computer technology.
Have a dream that one day can tour around.

**Comment by gnawux** [comment]
and the SRPM is here https://s3.amazonaws.com/hyper-install/hyper-0.4-1.el7.centos.x86_64.rpm , if you are interesting

**Comment by gnawux** [comment]
@CMGS 

Based on our tests and user reports, the following hyper and qemu RPMs will fix hyper on CentOS, could you remove all the hyper binaries under /usr/local/bin, and install the following prebuilt RPMs:

x86_64 binary packages:

> - [hyper-0.4-2.el7.centos.x86_64.rpm](https://s3.amazonaws.com/hyper-install/hyper-0.4-2.el7.centos.x86_64.rpm)
> -  [hyperstart-0.4-2.el7.centos.x86_64.rpm](https://s3.amazonaws.com/hyper-install/hyperstart-0.4-2.el7.centos.x86_64.rpm)
> - [qemu-hyper-2.4.1-2.el7.centos.x86_64.rpm](https://s3.amazonaws.com/hyper-install/qemu-hyper-2.4.1-2.el7.centos.x86_64.rpm)

**Comment by CMGS** [comment]
I install those RPMs on my host, it seems work well, nice job!

On Sat, Jan 30, 2016 at 11:41 AM, Xu Wang <notifications@github.com> wrote:

> @CMGS <https://github.com/CMGS>
>
> Based on our tests and user reports, the following hyper and qemu RPMs
> will fix hyper on CentOS, could you remove all the hyper binaries under
> /usr/local/bin, and install the following prebuilt RPMs:
>
> x86_64 binary packages:
>
>
>    - hyper-0.4-2.el7.centos.x86_64.rpm
>    <https://s3.amazonaws.com/hyper-install/hyper-0.4-2.el7.centos.x86_64.rpm>
>    - hyperstart-0.4-2.el7.centos.x86_64.rpm
>    <https://s3.amazonaws.com/hyper-install/hyperstart-0.4-2.el7.centos.x86_64.rpm>
>    - qemu-hyper-2.4.1-2.el7.centos.x86_64.rpm
>    <https://s3.amazonaws.com/hyper-install/qemu-hyper-2.4.1-2.el7.centos.x86_64.rpm>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hyperhq/hyper/issues/115#issuecomment-177059830>.
>



-- 

-CMGS
A simple coder.
Love travel, sports especially outdoor sports and computer technology.
Have a dream that one day can tour around.

**Comment by gnawux** [comment]
@CMGS thank you for your reports :)
