### ISSUE TITLE
Where can I download bios.bin and cbfs.rom？

### ISSUE THREAD

**Issue by hustcat** [hyperhq/hyper#12]
```sh
# ./hyperd --logtostderr
[HYPER INFO  0601 17:53:39 03555 hyperd.go] The config file is 
[HYPER INFO  0601 17:53:39 03555 daemon.go] The config: kernel=/var/lib/hyper/kernel, initrd=/var/lib/hyper/initrd.img
[HYPER INFO  0601 17:53:39 03555 daemon.go] The config: bridge=hyper0, ip=192.168.123.1/24
[HYPER INFO  0601 17:53:39 03555 daemon.go] The config: bios=, cbfs=
[HYPER ERROR 0601 17:53:39 03555 hyperd.go] The hyperd create failed, An error encountered returned from Docker daemon, client and server don't have same version (client : 1.17, server: 1.15)
```

**Comment by carmark** [comment]
@hustcat 

> [HYPER ERROR 0601 17:53:39 03555 hyperd.go] The hyperd create failed, An error encountered returned from Docker daemon, client and server don't have same version (client : 1.17, server: 1.15)

This error is caused by the different version between docker daemon and our docker rest api, you may have to update the docker.

By default, the bios.bin and cbfs.rom should be in /var/lib/hyper, you can verify it and put their paths in the **config** file if you want it.

**Comment by hustcat** [comment]
@carmark Thanks.

**Comment by gao-feng** [comment]
@hustcat boot.bin comes from qboot (https://github.com/bonzini/qboot.git), the README in qboot repo tells you how to generate cbfs.rom.
And the cbfstool comes from coreboot (https://github.com/coreboot/coreboot.git)

cbfs.rom is a different way to pass kernel&initrd to qemu. if hyperd find Bios and Cbfs from hyper config file, Kernel&Initrd will loss effect.
