### ISSUE TITLE
hyper ERROR: Error from daemon's response: VM response data is nil

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [hyperhq/hyper#122]
on Ubuntu 14.04.3 LTS , the hyper run failed  :

hyper images
REPOSITORY     TAG                 IMAGE ID                           CREATED             VIRTUAL SIZE
ubuntu         latest              a5a467fddcb8                2015-10-23 05:57:04            179.2 MB

service hyperd status
 * hyperd is running

hyper run ubuntu

hyper ERROR: Error from daemon's response: VM response data is nil

**Comment by gnawux** [comment]
@zhengxiaochuan-3 , sorry for the inconvenient.

what's the hyper version (build from source or downloaded binary)? And could you paste the log file in /var/log/hyper/  .

Thank you!

**Comment by zhengxiaochuan-3** [comment]
@gnawux

**Comment by gnawux** [comment]
@zhengxiaochuan-3 weird, is there anything not normal in the configuration of this machine? I think your operating system and image are both tested. And can you see any error messages when start the qemu command line manually?

    qemu -machine pc-i440fx-2.0,accel=kvm,usb=off -global kvm-pit.lost_tick_policy=discard -cpu host -drive if=pflash,file=/var/lib/hyper/bios-qboot.bin,readonly=on -drive if=pflash,file=/var/lib/hyper/cbfs-qboot.rom,readonly=on -realtime mlock=off -no-user-config -nodefaults -no-hpet -rtc base=utc,driftfix=slew -no-reboot -display none -boot strict=on -m 128 -smp 1 -qmp unix:/var/run/hyper/vm-NunbJiqFZu/qmp.sock,server,nowait -serial unix:/var/run/hyper/vm-NunbJiqFZu/console.sock,server,nowait -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x2 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x3 -chardev socket,id=charch0,path=/var/run/hyper/vm-NunbJiqFZu/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch1,path=/var/run/hyper/vm-NunbJiqFZu/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -fsdev local,id=virtio9p,path=/var/run/hyper/vm-NunbJiqFZu/share_dir,security_model=none -device virtio-9p-pci,fsdev=virtio9p,mount_tag=share_dir

**Comment by gnawux** [comment]
@zhengxiaochuan-3 

These are the information after the failure, could you paste the INFO messages before the message? And you can enable verbose log buy add the `-v` flag to the daemon (https://docs.hyper.sh/trouble_shooting/index.html)

And looks there is some device operation failure, did you compile qemu from source?

**Comment by zhengxiaochuan-3** [comment]
@gnawux 
 --- did you compile qemu from source
      no,I just install qemu with this cmd "apt-get install qemu"
all the daemon infos : 

[HYPER INFO  1101 16:32:46 03058 server.go] Calling POST /pod/run
[HYPER INFO  1101 16:32:46 03058 job.go] +job podRun({"id":"ubuntu-9105010387","containers":[{"name":"ubuntu-9105010387","image":"ubuntu","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":"","RestartPolicy":""}, no)
[HYPER INFO  1101 16:32:46 03058 pod.go] {"id":"ubuntu-9105010387","containers":[{"name":"ubuntu-9105010387","image":"ubuntu","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":"","RestartPolicy":""}
[HYPER INFO  1101 16:32:46 03058 pod.go] podArgs: {"id":"ubuntu-9105010387","containers":[{"name":"ubuntu-9105010387","image":"ubuntu","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":"","RestartPolicy":""}
[HYPER INFO  1101 16:32:46 03058 pod.go] leveldb: not found
[HYPER INFO  1101 16:32:46 03058 pod.go] Process the Containers section in POD SPEC
[HYPER INFO  1101 16:32:46 03058 tags.go] LookupImage Name is ubuntu
[HYPER INFO  1101 16:32:46 03058 container.go] ready to get the container(224e97d150b67792f4423ecd1fbe34eb451ba7b86c376a3c76fe1b18c9ff017c) info
[HYPER INFO  1101 16:32:46 03058 pod.go] The config: kernel=/var/lib/hyper/kernel, initrd=/var/lib/hyper/hyper-initrd.img
POD id is pod-chNJTxyOyO
[HYPER INFO  1101 16:32:46 03058 container.go] ready to get the container(224e97d150b67792f4423ecd1fbe34eb451ba7b86c376a3c76fe1b18c9ff017c) info
[HYPER INFO  1101 16:32:46 03058 qemu_process.go] cmdline arguments: -machine pc-i440fx-2.0,accel=kvm,usb=off -global kvm-pit.lost_tick_policy=discard -cpu host -drive if=pflash,file=/var/lib/hyper/bios-qboot.bin,readonly=on -drive if=pflash,file=/var/lib/hyper/cbfs-qboot.rom,readonly=on -realtime mlock=off -no-user-config -nodefaults -no-hpet -rtc base=utc,driftfix=slew -no-reboot -display none -boot strict=on -m 128 -smp 1 -qmp unix:/var/run/hyper/vm-NunbJiqFZu/qmp.sock,server,nowait -serial unix:/var/run/hyper/vm-NunbJiqFZu/console.sock,server,nowait -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x2 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x3 -chardev socket,id=charch0,path=/var/run/hyper/vm-NunbJiqFZu/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch1,path=/var/run/hyper/vm-NunbJiqFZu/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -fsdev local,id=virtio9p,path=/var/run/hyper/vm-NunbJiqFZu/share_dir,security_model=none -device virtio-9p-pci,fsdev=virtio9p,mount_tag=share_dir
[HYPER INFO  1101 16:32:46 03058 pod.go] Parsing envs for container 0: 0 Evs
[HYPER INFO  1101 16:32:46 03058 pod.go] The fs type is dir
[HYPER INFO  1101 16:32:46 03058 pod.go] WorkingDir is 
[HYPER INFO  1101 16:32:46 03058 pod.go] Image is /224e97d150b67792f4423ecd1fbe34eb451ba7b86c376a3c76fe1b18c9ff017c/rootfs
[HYPER INFO  1101 16:32:46 03058 pod.go] Container Info is 
&{224e97d150b67792f4423ecd1fbe34eb451ba7b86c376a3c76fe1b18c9ff017c  /224e97d150b67792f4423ecd1fbe34eb451ba7b86c376a3c76fe1b18c9ff017c/rootfs dir  [] [/bin/bash] map[]}
[HYPER INFO  1101 16:32:46 03058 pod.go] container 0 created 224e97d150b67792f4423ecd1fbe34eb451ba7b86c376a3c76fe1b18c9ff017c, workdir , env: map[]
[HYPER INFO  1101 16:32:46 03058 hypervisor.go] main event loop got message 22(COMMAND_RUN_POD)
[HYPER INFO  1101 16:32:46 03058 vm_states.go] got spec, prepare devices
[HYPER INFO  1101 16:32:46 03058 vm.go] hyperHandlePodEvent pod pod-chNJTxyOyO, vm vm-NunbJiqFZu
[HYPER INFO  1101 16:32:46 03058 vm.go] hyperHandlePodEvent pod pod-chNJTxyOyO, vm vm-NunbJiqFZu
[HYPER INFO  1101 16:32:46 03058 context.go] VM vm-NunbJiqFZu: state change from  to 'STARTING'
[HYPER INFO  1101 16:32:46 03058 hypervisor.go] main event loop got message 13(EVENT_INTERFACE_ADD)
[HYPER INFO  1101 16:32:46 03058 qmp_wrapper.go] send net to qemu at 21
[HYPER INFO  1101 16:32:46 03058 qmp_handler.go] got new session during initializing
[HYPER INFO  1101 16:32:46 03058 qemu_process.go] qemu daemon pid 3131.
[HYPER INFO  1101 16:32:46 03058 qemu_process.go] starting daemon with pid: 3131
[HYPER WARN  1101 16:32:56 03058 qmp_handler.go] Initializer Timeout.
[HYPER ERROR 1101 16:32:56 03058 qmp_handler.go] QMP initialize timeout
[HYPER INFO  1101 16:32:56 03058 hypervisor.go] main event loop got message 32(ERROR_INIT_FAIL)
[HYPER ERROR 1101 16:32:56 03058 vm_states.go] QMP Init timeout
[HYPER ERROR 1101 16:32:56 03058 vm_states.go] Shutting down because of an exception: Fail during init pod running environment
[HYPER INFO  1101 16:32:56 03058 context.go] VM vm-NunbJiqFZu: state change from STARTING to 'TERMINATING'
[HYPER INFO  1101 16:32:56 03058 vm.go] Get the response from VM, VM id is vm-NunbJiqFZu!
[HYPER INFO  1101 16:32:56 03058 hypervisor.go] main event loop got message 25(COMMAND_SHUTDOWN)
[HYPER INFO  1101 16:32:56 03058 vm_states.go] got event during terminating
[HYPER ERROR 1101 16:32:56 03058 init_comm.go] Cannot connect to hyper socket dial unix /var/run/hyper/vm-NunbJiqFZu/hyper.sock: connect: connection refused
[HYPER INFO  1101 16:32:56 03058 hypervisor.go] main event loop got message 32(ERROR_INIT_FAIL)
[HYPER INFO  1101 16:32:56 03058 vm_states.go] got event during terminating
[HYPER ERROR 1101 16:32:56 03058 tty.go] Cannot connect to tty socket dial unix /var/run/hyper/vm-NunbJiqFZu/tty.sock: connect: connection refused
[HYPER ERROR 1101 16:32:56 03058 init_comm.go] failed to connected to /var/run/hyper/vm-NunbJiqFZu/console.sock dial unix /var/run/hyper/vm-NunbJiqFZu/console.sock: connect: no such file or directory
[HYPER ERROR 1101 16:32:56 03058 qmp_handler.go] failed to connected to /var/run/hyper/vm-NunbJiqFZu/qmp.sock dial unix /var/run/hyper/vm-NunbJiqFZu/qmp.sock: connect: connection refused
[HYPER INFO  1101 16:32:56 03058 hypervisor.go] main event loop got message 32(ERROR_INIT_FAIL)
[HYPER INFO  1101 16:32:56 03058 vm_states.go] got event during terminating
[HYPER INFO  1101 16:33:06 03058 hypervisor.go] main event loop got message 3(EVENT_VM_TIMEOUT)
[HYPER WARN  1101 16:33:06 03058 vm_states.go] VM did not exit in time, try to stop it
[HYPER ERROR 1101 16:33:06 03058 vm_states.go] Shutting down because of an exception: vm terminating timeout
[HYPER INFO  1101 16:33:06 03058 vm.go] Got response: 7: vm terminating timeout
[HYPER INFO  1101 16:33:16 03058 qemu_process.go] kill Qemu... 3131
[HYPER INFO  1101 16:33:16 03058 hypervisor.go] main event loop got message 2(EVENT_VM_KILL)
[HYPER INFO  1101 16:33:16 03058 vm_states.go] Got VM force killed message, go to cleaning up
[HYPER INFO  1101 16:33:16 03058 vm_states.go] VM has exit...
[HYPER INFO  1101 16:33:16 03058 vm.go] Got response: 2: VM shut down
[HYPER ERROR 1101 16:33:16 03058 pod.go] VM response data is nil
[HYPER INFO  1101 16:33:16 03058 devicemap.go] need unmount aufs /224e97d150b67792f4423ecd1fbe34eb451ba7b86c376a3c76fe1b18c9ff017c/rootfs
[HYPER INFO  1101 16:33:16 03058 job.go] -job podRun({"id":"ubuntu-9105010387","containers":[{"name":"ubuntu-9105010387","image":"ubuntu","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":"","RestartPolicy":""}, no) ERR: VM response data is nil
[HYPER INFO  1101 16:33:16 03058 devicemap.go] remove network card 0: 192.168.123.3
[HYPER INFO  1101 16:33:16 03058 context.go] VM vm-NunbJiqFZu: state change from TERMINATING to 'DESTROYING'
[HYPER ERROR 1101 16:33:16 03058 server.go] Handler for POST /pod/run returned error: VM response data is nil
[HYPER ERROR 1101 16:33:16 03058 server.go] HTTP Error: statusCode=500 VM response data is nil
[HYPER INFO  1101 16:33:16 03058 volume_linux.go] Ready to unmount the target : /var/run/hyper/vm-NunbJiqFZu/share_dir/224e97d150b67792f4423ecd1fbe34eb451ba7b86c376a3c76fe1b18c9ff017c/rootfs
[HYPER INFO  1101 16:33:16 03058 hypervisor.go] main event loop got message 14(EVENT_INTERFACE_DELETE)
[HYPER INFO  1101 16:33:16 03058 devicemap.go] interface 0 released
[HYPER INFO  1101 16:33:16 03058 vm_states.go] Unplug interface return with true
[HYPER INFO  1101 16:33:16 03058 hypervisor.go] main event loop got message 7(EVENT_CONTAINER_DELETE)
[HYPER INFO  1101 16:33:16 03058 devicemap.go] container 0 umounted
[HYPER INFO  1101 16:33:16 03058 vm_states.go] Unplug container return with true
[HYPER INFO  1101 16:33:34 03058 hypervisor.go] main event loop got message 3(EVENT_VM_TIMEOUT)
[HYPER INFO  1101 16:33:34 03058 vm_states.go] Device removing timeout

**Comment by gnawux** [comment]
@zhengxiaochuan-3 looks the qemu didn't initialized in 10 seconds, this is not a normal case. I think reboot or restart might help...

And the current `master` branch improved the vm start process, you may have a try to [Build from Source](https://docs.hyper.sh/get_started/install/build.html). And we are also planning to provide new version of binary soon.

**Comment by zhengxiaochuan-3** [comment]
@gnawux 
system rebooted, but hyper run still failed.
ok,looking for new version of binary hyper.
thanks a lot .

**Comment by zhengxiaochuan-3** [comment]
@gnawux 

I builded hyper from source on centos7.1 , no more this issue again.

**Comment by carmark** [comment]
No more issues with the master source code.
