### ISSUE TITLE
hyper can not pull images from private registry (v1)

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [hyperhq/hyper#125]
[HYPER INFO  1103 14:22:13 01368 job.go] -job pull(192.168.212.23:5060/jdos2base/jd_new_base_img_6) ERR: invalid registry endpoint https://192.168.212.23:5060/v0/: unable to ping registry endpoint https://192.168.212.23:5060/v0/
v2 ping attempt failed with error: Get https://192.168.212.23:5060/v2/: EOF
 v1 ping attempt failed with error: Get https://192.168.212.23:5060/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 192.168.212.23:5060` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/192.168.212.23:5060/ca.crt

I think this is a bug. how should i add  "--insecure-registry 192.168.212.23:5060" to the hyperd's arguments .this is a dockerd solution advise? LOL

[root@node-65-148 hyper]# hyperd --insecure-registry 192.168.212.23:5060
flag provided but not defined: -insecure-registry
Usage:
  hyperd [OPTIONS]

Application Options:
  --nondaemon            Not daemonize
  --config=""            Configuration for hyperd
  --v=0                  Log level fro V logs
  --log_dir              Log directory
  --host                 Host address and port for hyperd(such as --host=tcp://127.0.0.1:12345)
  --logtostderr          Log to standard error instead of files
  --alsologtostderr      Log to standard error as well as files

Help Options:
  -h, --help             Show this help message

**Comment by carmark** [comment]
Hello @zhengxiaochuan-3 

The option `--insecure-registry` is not supported now, we will consider to add it.  Could you please try a workaround like the warning said?  

>simply place the CA certificate at /etc/docker/certs.d/192.168.212.23:5060/ca.crt
