### ISSUE TITLE
No where to specific Docker options

### ISSUE THREAD

**Issue by mckelvin** [hyperhq/hyper#128]
The official docker registry is slow in my network environment. So I want to specific a registry mirror, but failed to find anywhere to specific Docker options like `--registry-mirror` in `/opt/hyper/etc/hyper/config`. I've read the documentation, but it doesn't work.

https://docs.hyper.sh/reference/containers.html says a image can be in form `[registry]/image[:tag]`:

So, I tried

```
$ hyper pull secret.m.daocloud.io/ubuntu:latest                                                                                   2 ↵
hyper ERROR: invalid registry endpoint https://secret.m.daocloud.io/v0/: unable to ping registry endpoint https://secret.m.daocloud.io/v0/
v2 ping attempt failed with error: Get https://secret.m.daocloud.io/v2/: dial tcp 123.59.43.85:443: connection refused
 v1 ping attempt failed with error: Get https://secret.m.daocloud.io/v1/_ping: dial tcp 123.59.43.85:443: connection refused. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry secret.m.daocloud.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/secret.m.daocloud.io/ca.crt
```

I my case, only `http` is supported for `secret.m.daocloud.io`. I followed the output and tried to add `--insecure-registry secret.m.daocloud.io` to the daemon's arguments(in `/Library/LaunchDaemons/sh.hyper.hyper.plist` since I can't find a docker config file inside `/opt/hyper/` :( ), but `/opt/hyper/bin/hyperd` doesn't accept the argument.

**Comment by mckelvin** [comment]
cc https://github.com/hyperhq/hyper/issues/59

**Comment by carmark** [comment]
Yes, some options(such as `--registry-mirror` and listed options in https://github.com/hyperhq/hyper/issues/59) are not supported now.  We have to use VPN to access the docker hub, the `daocloud` mirror seems not a valid registry.  You can specify the private registry if you want to set it up on your network.

Thanks for your trying and interesting.

**Comment by carmark** [comment]
fixed by https://github.com/hyperhq/hyper/pull/149
