### ISSUE TITLE
The hyperd create failed, hyperd can not support docker's backing storage: vfs

### ISSUE THREAD

**Issue by luluprat** [hyperhq/hyper#129]
hello i try this on ubuntu 15.04
hyperd --nondaemon
[HYPER INFO  1111 10:01:10 11795 docker.go] success to create docker
[HYPER INFO  1111 10:01:10 11795 daemon.go] The config: kernel=/var/lib/hyper/kernel, initrd=/var/lib/hyper/hyper-initrd.img
[HYPER INFO  1111 10:01:10 11795 daemon.go] The config: vbox image=
[HYPER INFO  1111 10:01:10 11795 daemon.go] The config: bridge=, ip=
[HYPER INFO  1111 10:01:10 11795 daemon.go] The config: bios=/var/lib/hyper/bios-qboot.bin, cbfs=/var/lib/hyper/cbfs-qboot.rom
[HYPER ERROR 1111 10:01:10 11795 overlay.go] 'overlay' not found as a supported filesystem on this host. Please ensure kernel is new enough and has overlay support loaded.
[HYPER ERROR 1111 10:01:10 11795 driver_linux.go] ef53
[HYPER ERROR 1111 10:01:10 11795 deviceset.go] Udev sync is not supported. This will lead to unexpected behavior, data loss and errors. For more information, see https://docs.docker.com/reference/commandline/cli/#daemon-storage-driver-option
[HYPER INFO  1111 10:01:10 11795 daemon.go] Creating images graph
[HYPER INFO  1111 10:01:10 11795 daemon.go] Creating repository list
[HYPER INFO  1111 10:01:10 11795 daemon.go] Loading containers: done.
[HYPER INFO  1111 10:01:10 11795 docker.go] Daemon has completed initialization
[HYPER ERROR 1111 10:01:10 11795 hyperd.go] The hyperd create failed, hyperd can not support docker's backing storage: vfs

**Comment by gnawux** [comment]
@luluprat sorry for the inconvenient. it looks the daemon tried to work with overlayfs driver but did not success. Could you try to add

    StorageDriver=aufs

or

    StorageDriver=devicemapper

in config file `/etc/hyper/config`

**Comment by luluprat** [comment]
thnks for you reply
but they didn't work either
same error
The hyperd create failed, hyperd can not support docker's backing storage: vfs

**Comment by gnawux** [comment]
@luluprat we will check it in detail. by the way: did you installed the binary from the project homepage? If so, we will update the binary packages soon.

**Comment by luluprat** [comment]
i did :+1: curl -sSL https://hyper.sh/install | bash

**Comment by luluprat** [comment]
are you planning to support ubuntu 15.04 ?

**Comment by gnawux** [comment]
@luluprat If it does not work under 15.04, there should be a bug. We will update the binary package in hours.

**Comment by luluprat** [comment]
hello

i tried with the right kernel and everything is fine
it was a kernel from the cloud provider (specific)

**Comment by gnawux** [comment]
ok, and we will still update the package soon, as It fixed several bugs and has some new features.
