### ISSUE TITLE
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c5330000, 181207040, 0) failed; error='Cannot allocate memory' (errno=12)

### ISSUE THREAD

**Issue by luluprat** [hyperhq/hyper#130]
i run 
hyper run elasticsearch --memory=128 
POD id is pod-QAFKDBEpuB
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c5330000, 181207040, 0) failed; error='Cannot allocate memory' (errno=12)

There is insufficient memory for the Java Runtime Environment to continue.
Native memory allocation (mmap) failed to map 181207040 bytes for committing reserved memory.
An error report file with more information is saved as:
/tmp/hs_err_pid2.log

**Comment by luluprat** [comment]
i tried 
hyper run elasticsearch --memory=256

there is no error  but  i didn't have the prompt come back

**Comment by gnawux** [comment]
to specify memory for a Pod, use `hyper run -m 256 elasticsearch`. [the document for run is here](https://docs.hyper.sh/reference/run.html). And you can configure the pod with a [Pod file](https://docs.hyper.sh/reference/podfile.html), and run it with `hyper run -p podfile`.

**Comment by carmark** [comment]
long time no update, so close
