### ISSUE TITLE
no bash prompt in created container

### ISSUE THREAD

**Issue by huikang** [hyperhq/hyper#139]
Hi,
I installed hyper using the install.sh script. When I created a pod, the VM and container seem to be launched. However, there is no bash prompt,

```
ls
bin   dev  home  lib64	mnt  proc  run	 srv  tmp  var
boot  etc  lib	 media	opt  root  sbin  sys  usr

exit
Successfully attached to pod(pod-RXIKpDDvLc)
End of CmdExec(), Waiting for hijack to finish
```

Is this a bug of hyper or anything wrong with my configuration? Thanks.

My system info:
```
# hyper info
Images: 4
Containers: 1
PODs: 1
Storage Driver: overlay
  Backing Filesystem: extfs
Hyper Root Dir: /var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: kvm
Total Memory: 3.9 MB
Operating System: Ubuntu 15.04

QEMU emulator version 2.4.1,
```

**Comment by gnawux** [comment]
for the latest hyper, use 

    hyper run -t ubuntu /bin/bash

docs: https://docs.hyper.sh/reference/run.html

This change is introduced by the `hyper log` support.

**Comment by huikang** [comment]
it works. thanks, @gnawux
