### ISSUE TITLE
Remove docker related pre-requirements

### ISSUE THREAD

**Issue by oilbeater** [hyperhq/hyper#16]
As far as I can see, what hyper needs from docker is only downloading images. 

If this part of job can be done by registry API inside hyper, users can install less pre-requirement software. And this can really  make "Hyper = Hypervisor + Kernel + Docker Image" concept more clearly. As for myself, the relation between docker and hyper confused me for a long time.

**Comment by gnawux** [comment]
Thank you @oilbeater , this issue will be closed after eliminate all docker dependencies.

**Comment by carmark** [comment]
fixed by https://github.com/hyperhq/hyper/commit/b569471193d5a730deb5e509ec2fb1fd22c659d4
