### ISSUE TITLE
OSX 10.10+ Hypervisor.framework support?

### ISSUE THREAD

**Issue by DylanSale** [hyperhq/hyper#164]
Is it possible to use Hyper with the Hypervisor.framework added in OSX 10.10 to avoid the dependency on virtualbox? I'm just curious for the most part, I'd like to have a more "native" docker experience for OSX out of the box.

EDIT: Also this would allow apps built using docker/hyper to be available on the App Store

**Comment by gnawux** [comment]
@DylanSale so far, the only open source hypervisor support Hypervisor.framwork is xhyve, and it lacks some feature we need. We are also trying do some work on that, but current is is still under development.
