### ISSUE TITLE
Failed to run centos:7

### ISSUE THREAD

**Issue by darkheaven1983** [hyperhq/hyper#17]
I got an error message when I tried to run CentOS7 using hyper. Specifying a command doesn't work either. More details as followed.

[root@registry ~]# docker --version
Docker version 1.6.0, build 8aae715/1.6.0

[root@registry ~]# hyper run centos:7 
hyper ERROR: An error encountered returned from Docker daemon, No command specified

[HYPER INFO  0610 12:24:^@16 29888 server.go] Calling POST /pod/run
[HYPER INFO  0610 12:24:^@16 29888 job.go] +job podRun({"id":"centos:7-3761847811","containers":[{"name":"centos:7-3761847811","image":"centos:7","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""})
[HYPER INFO  0610 12:24:^@16 29888 pod.go] {"id":"centos:7-3761847811","containers":[{"name":"centos:7-3761847811","image":"centos:7","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""}
[HYPER ERROR 0610 12:24:^@16 29888 pod.go] An error encountered returned from Docker daemon, No command specified
[HYPER ERROR 0610 12:24:^@16 29888 pod.go] An error encountered returned from Docker daemon, No command specified
[HYPER INFO  0610 12:24:^@16 29888 vm_states.go] got shutdown command, shutting down
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] got new session during initializing
[HYPER INFO  0610 12:24:^@16 29888 init_comm.go] Wating for init messages...
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] begin qmp init...
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] got qmp welcome, now sending command qmp_capabilities
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] waiting for response
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] got for response
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] QMP connection initialized
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] QMP initialzed, go into main QMP loop
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] Begin receive QMP message
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] session finished, buffer size 1
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] Shutdown, quit QMP receiver
[HYPER INFO  0610 12:24:^@16 29888 qmp_handler.go] got QMP shutdown event, quit...
[HYPER INFO  0610 12:24:^@16 29888 vm_states.go] Got QMP shutdown event
[HYPER INFO  0610 12:24:^@16 29888 vm_states.go] VM Context closed.
[HYPER ERROR 0610 12:24:^@16 29888 pod.go] An error encountered returned from Docker daemon, No command specified
[HYPER INFO  0610 12:24:^@16 29888 job.go] -job podRun({"id":"centos:7-3761847811","containers":[{"name":"centos:7-3761847811","image":"centos:7","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""}) ERR: An error encountered returned from Docker daemon, No command specified

[HYPER ERROR 0610 12:24:^@16 29888 server.go] Handler for POST /pod/run returned error: An error encountered returned from Docker daemon, No command specified
[HYPER ERROR 0610 12:24:^@16 29888 server.go] HTTP Error: statusCode=500 An error encountered returned from Docker daemon, No command specified
[HYPER INFO  0610 12:24:^@16 29888 qemu_process.go] console output end
[HYPER ERROR 0610 12:24:^@16 29888 tty.go] read tty data failed
[HYPER ERROR 0610 12:24:^@16 29888 init_comm.go] read init data failed
[HYPER ERROR 0610 12:24:^@16 29888 init_comm.go] read init message failed... EOF

**Comment by carmark** [comment]
@darkheaven1983  Thanks for you reported this issue.  Do you encounter this issue if you specific a command for the `hyper run`, such as `hyper run centos:7 /bin/sh`?

Regards,

**Comment by carmark** [comment]
@darkheaven1983 

Could you please remove that centos:7 image and pull it again?  I did the test locally, but it works well.  I am not sure whether the image of centos:7 has issue, so you can remove and try it again?

Also could you please try `hyper run ubuntu` if it won't work.

Thanks,

**Comment by darkheaven1983** [comment]
@carmark Removing the image and downloading it again works. Closing this issue....
