### ISSUE TITLE
Start pod with volume failed

### ISSUE THREAD

**Issue by feiskyer** [hyperhq/hyper#173]
```sh
# hyper run -p pod.json
POD id is pod-iNOxgfNfoo
Time to run a POD is 3724 ms
[root@k8s ~]# hyper list
POD ID              POD Name            VM name             Status
pod-EiadAzNPDM      myweb                                   pending
pod-aOefldwBeD      myweb                                   failed
pod-iNOxgfNfoo      mewed                                   failed

# hyper info
Hyper Root Dir: /var/lib/hyper
Index Server Address: https://index.docker.io/v1/
Execution Driver: libvirt
Total Memory: 7.4 MB
Operating System: CentOS Linux 7 (Core)
```

pod.json

```json
{
    "id": "myweb",
    "tty": true,

    "resource": {
        "vcpu": 1,
        "memory": 128
    },

    "containers" : [{
        "image": "nginx",
        "volumes": [{
            "volume": "prod_log",
            "path": "/var/log",
            "readOnly": false
         }]
    }],

    "volumes": [{
            "name": "prod_log",
            "source": "/mnt",
            "driver": "vfs"
    }
```

**Comment by gnawux** [comment]
my test has passed with my runv patch for json:

<pre>
{
        "id": "test-container-volume",
        "containers" : [{
            "name": "c1",
            "image": "busybox",
            "command": ["/bin/sh", "-c", "grep -q 'hello, world' /mnt/with-volume-test-1 && df | grep -q '/var/log' && echo 'container 1 OK'"],
            "volumes": [{
                "volume": "log",
                "path": "/var/log",
                "readOnly": false
             },{
                "volume": "tmp",
                "path": "/mnt",
                "readOnly": false
             }]
        },
        {
            "name": "c2",
            "image": "busybox",
            "workdir": "/",
            "command": ["/bin/sh", "-c", "echo 'container-2 OK' > /mnt/with-volume-test-2"],
            "volumes": [{
                "volume": "log",
                "path": "/var/log",
                "readOnly": false
             },{
                "volume": "tmp",
                "path": "/mnt",
                "readOnly": false
             }]
        }],
        "resource": {
            "vcpu": 1,
            "memory": 512
        },
        "files": [],
        "volumes": [{
            "name": "log",
            "source": "",
            "driver": ""
        },{
            "name": "tmp",
            "source": "TMPDIR",
            "driver": "vfs"
        }],
        "tty": true
}
</pre>

**Comment by carmark** [comment]
This `failed` is caused by the finish of default command.  It will be `running` when you setup the `command` to `/bin/sh` as follow:

```
{
    "id": "myweb",
    "tty": true,

    "resource": {
        "vcpu": 1,
        "memory": 128
    },

    "containers" : [{
        "image": "nginx",
	    "command": ["/bin/sh"],
        "volumes": [{
            "volume": "prod_log",
            "path": "/var/log",
            "readOnly": false
         }]
    }],

    "volumes": [{
            "name": "prod_log",
            "source": "/mnt",
            "driver": "vfs"
    }]
}
```

**Comment by feiskyer** [comment]
@carmark It's so weird to run `/bin/sh` for `nginx` image.
