### ISSUE TITLE
Install hyper will affect the vagrant(virtualbox)?

### ISSUE THREAD

**Issue by hjianhao** [hyperhq/hyper#18]
My Host OS is ubuntu 15.0. I had install virtualbox and vagrant, they works well. 

I install the hyper today, it works fine. But when I start the VMs created by vagrant, they all faied, the error informations are : The guest machine entered an invalid state while waiting for it to boot. Valid states are 'starting, running'. The machine is in the 'poweroff'

Does the hyper affect vagrant?

By the way, how uninstall the hyper? I only see installation guide for hyper.

**Comment by carmark** [comment]
Hello @hjianhao ,

Thanks for you to try the hyper. The hyper uses Qemu+KVM as the virtual machine, I think you installed the KVM and Qemu.  However, the vbox can not run while the kvm kernel module is loaded.

If you want to run the vbox, you may remove the kvm module and run it again.

For the Hyper uninstall, you can stop the Hyper service and remove the files from `/var/lib/hyper` and the binaries.

Thanks,
-Lei

**Comment by hjianhao** [comment]
Thanks, I use the rmmod kvm and rmmod kvm_intel to remove the kvm modules, then I can start the virutalbox VM.
But I add the kvm modules by modprobe again, virtualbox VM can still start successfully. A little confused. :)
