### ISSUE TITLE
POD starts on centos and exits

### ISSUE THREAD

**Issue by PRADEEPKJ** [hyperhq/hyper#186]
Hi all,

I am new to Hyper. I have installed it on centos7. Built the qemu as per the requirement. The hyperd starts succesfully and runs.
I could even runt the POD using below command

hyper run centos:latest

Runs with a POD ID
POD id is pod-UKeiZPrWzl

After some time it exits with below message. Is this correct behavior or I have something wrong?

Successfully attached to pod(pod-UKeiZPrWzl)
End of CmdExec(), Waiting for hijack to finish.

Please help me to resolve.

Regards,
Pradeep

**Comment by gnawux** [comment]
For CentOS 7.x, could you remove all the hyper binaries under /usr/local/bin, and install the following prebuilt RPMs:

x86_64 binary packages:

> - [hyper-0.4-2.el7.centos.x86_64.rpm](https://s3.amazonaws.com/hyper-install/hyper-0.4-2.el7.centos.x86_64.rpm)
> -  [hyperstart-0.4-2.el7.centos.x86_64.rpm](https://s3.amazonaws.com/hyper-install/hyperstart-0.4-2.el7.centos.x86_64.rpm)
> - [qemu-hyper-2.4.1-2.el7.centos.x86_64.rpm](https://s3.amazonaws.com/hyper-install/qemu-hyper-2.4.1-2.el7.centos.x86_64.rpm)

**Comment by PRADEEPKJ** [comment]
Hi Wang,

Thanks, I will try those.

Regards,
Pradeep

**Comment by gnawux** [comment]
close as the RPMs works

**Comment by PRADEEPKJ** [comment]
Hi,

I was trying to add a -fsdev device in runv

like below

"-fsdev", fmt.Sprintf("local,id=virtio9pEX,path=%s,security_model=none",
ctx.ExDir),
"-device", fmt.Sprintf("virtio-9p-pci,fsdev=virtio9pEX,mount_tag=%s",
hypervisor.ExDirTag),

But when I start the container, it hangs and get Timeout message as below
container run error: Run container timeout!.

Any idea. How can I add a external device?

Thanks,
Pradeep
