### ISSUE TITLE
Is there any network options for hyper?

### ISSUE THREAD

**Issue by hjianhao** [hyperhq/hyper#19]
I start the pod and find the pod using the private network, can not access it from ouside. What's the network models of the hyper? Do you have the network options for the pod just like docker and vagrant? :)

**Comment by hjianhao** [comment]
I can not find any clue from your documentation. :)

**Comment by gao-feng** [comment]
Hi, right now hyper only support linux birdge, the default ip subnet is 192.168.123.1/24, the default bridge is hyper0 and its ip address is 192.168.123.1.  You can change the hyper bridge and ip subnet
by change the hyper config, then restart hyperd.

If you want to access the pod, you can add the "ports":[{"containerPort": 80,"hostPort": 8088}] under the containers section. then access the hyper0-ip:hostPort.
