### ISSUE TITLE
hyper ERROR: Cannot connect to the Hyper daemon. Is 'hyperd' running on this host?

### ISSUE THREAD

**Issue by qcbupt** [hyperhq/hyper#21]
After I hyper run -p pod.json, my hyper shutdown, and no hyperd service.

root@bjwj:/home/ubuntu/volumes# hyper run -p myweb.json 
hyper ERROR: An error occurred trying to connect: Post http:///var/run/hyper.sock/v0.2/pod/run?podArgs=%7B%22id%22%3A+%22myweb%22%2C%22tty%22%3A+true%2C%22resource%22%3A+%7B%22vcpu%22%3A+1%2C%22memory%22%3A+128%7D%2C%22containers%22+%3A+%5B%7B%22name%22%3A+%22myweb%22%2C%22image%22%3A+%22jdeathe%2Fcentos-ssh%22%2C%22command%22%3A+%5B%22%2Fbin%2Fsh%22%5D%2C%09%22workdir%22%3A+%22%2Froot%22%2C%22envs%22%3A++%5B%7B%22env%22%3A+%22JAVA_OPT%22%2C+%22value%22%3A+%22-XMx%3D256m%22+%7D%5D%2C%22ports%22%3A%5B%7B%22containerPort%22%3A+80%2C%09%22hostPort%22%3A+8000+%7D%5D%2C%22volumes%22%3A+%5B%7B%22path%22%3A+%22%2Fhome%2Fubuntu%2Fvolumes%2Fvol_test_1%22%2C%22volume%22%3A+%22name%22%2C%22readOnly%22%3A+false%7D%5D+%7D%5D%7D%0A%0A: EOF
root@bjwj:/home/ubuntu/volumes# hyper list
hyper ERROR: Cannot connect to the Hyper daemon. Is 'hyperd' running on this host?
root@bjwj:/home/ubuntu/volumes# service hyperd status
 * hyperd is not running

My pod.json is ：
{"id": "myweb","tty": true,"resource": {"vcpu": 1,"memory": 128},"containers" : [{"name": "myweb","image": "jdeathe/centos-ssh","command": ["/bin/sh"], "workdir": "/root","envs":  [{"env": "JAVA_OPT", "value": "-XMx=256m" }],"ports":[{"containerPort": 80, "hostPort": 8000 }],"volumes": [{"path": "/home/ubuntu/volumes/vol_test_1","volume": "name","readOnly": false}] }]}

**Comment by gnawux** [comment]
did you start hyperd service

- if it was started, find the log in `/var/log/hyper/`
- if not, start it first.

And in your pod file, the `containers.$.volumes` field is a reference to the top level volume description. If you want to use volume, reference this example:

https://github.com/hyperhq/hyper/blob/master/examples/with-volume.pod

Thank you
