### ISSUE TITLE
make ignores DESTDIR

### ISSUE THREAD

**Issue by justin8** [hyperhq/hyper#227]
I'm trying to build hyper in to a package for Arch linux, and it is ignoring the DESTDIR setting for make:

```
$ make DESTDIR=/tmp/foo install
...
/usr/bin/install -c hyper /usr/local/bin
/usr/bin/install: cannot create regular file '/usr/local/bin/hyper': Permission denied
Makefile:783: recipe for target 'install-exec-local' failed
```

**Comment by gnawux** [comment]
Hi @justin8 ,

You may set the destination with `./configure --prefix=/tmp/foo` to install to `/tmp/foo/bin`, or `./configure --bindir=/tmp/foo` to install binaries to `/tmp/foo`

**Comment by justin8** [comment]
ok, I'll give that a go. Thanks.
