### ISSUE TITLE
Is it necessary to use docker/go-units in Hyper to make unit compatile with docker?

### ISSUE THREAD

**Issue by allencloud** [hyperhq/hyper#251]
Hi ,all:

I found that in Hyper size unit such as KB, MB is not the same concept of Docker.
I am not saying that units in Hyper is incorrect. 
But compatibility with Docker is better.

like below:
https://github.com/hyperhq/hyper/blob/master/client/images.go#L87-L95
```
	if s < 1024 {
		return size + " B"
	} else if s < 1024*1024 {
		rtn = float64(s) / 1024.0
		return fmt.Sprintf("%.1f KB", rtn)
	} else {
		rtn = float64(s) / (1024.0 * 1024.0)
		return fmt.Sprintf("%.1f MB", rtn)
	}
```

Usually docker/go-units will classify MB and MiB.

**Comment by gnawux** [comment]
I agree with you, Thank you

**Comment by allencloud** [comment]
close this via #252
