### ISSUE TITLE
Inconsitencies with hyper and documentatiion

### ISSUE THREAD

**Issue by zenny** [hyperhq/hyper#265]
Hi,

Found a lot of inconsistencies in hyper(ctl) app and documentation (https://docs.hyper.sh/).

Whether pulled the tarballed image or built from source, hyper(ctl) does not support the 'volume create/ls/rm' and 'fip'-related options.

Above all, 'hypter(ctl) --version' is unavailable to report bugs (both in the precompiled tarball and freshly build from this repo). Strange!

Is this a feature/bug/omission?

**Comment by gnawux** [comment]
hi @zenny , 

The current https://docs.hyper.sh is for new launched https://hyper.sh service, which is based on this project.

We are moving the docs and installer of the open source project to a proper url, it will ready soon.

Thank you

**Comment by zenny** [comment]
@gnawux that means the "open source" code over here is a crippled version which even does not address the basic requirements of containerization, it seems. The entire approach seems _flawed_ in open source model where you do not cripple the source code nor features, but charge for a service.

**Comment by gnawux** [comment]
@zenny for the containerization part, the public service and the open source project share the same code base. And the public container host service integrates the hyper, hypernetes project and some other functionalities. 

During the development and serving of the public service, we also find bugs and improve the quality of open source project. You can find many fix and improvement in the recent PRs. Most of them comes from the service operating, and serve for both open source community and the public service.

**Comment by zenny** [comment]
> the public service and the open source project share the same code base.

@gnawux Then why is there an omission of very essential parameters (like volume creation and destruction, fip and stats in the open source code?

That could be the reason there is not so much traction in this project though sounds interesting, just my guess. 

Xiexie

**Comment by gnawux** [comment]
@zenny these subcommand are not features of the container engine, they are the feature of hypernetes project. In the public service, we provide a docker-compatible cmdline interface to users, then users can use a command line tools to manage their containers and other resources. If like, you can also check the hyperhq/hypernetes project.

**Comment by zenny** [comment]
@gnawux very confusing like Chinese characters because the documentation to this repo points to http://docs.hyper.sh and nowhere else. Do you mean that the documentation link is randomly selected? 

Shall check hypernetes if that is so.

**Comment by gnawux** [comment]
This repo was point to hyper.sh, and we have a new domain name (hypercontainer.io) for it, dedicate for the open source project. And the source of docs are still here https://github.com/hyperhq/book .

**Comment by zenny** [comment]
The problem with this repo is scattered bits of information over scattered sites, causing 'information pollution". FreeBSD and ArchLinux are two best places to learn from, just my two _fen_s. :-)

**Comment by gnawux** [comment]
As I have said, the new site for the project is not ready yet.
