### ISSUE TITLE
hyperd thread seems dead when run command " hyper run ubuntu"

### ISSUE THREAD

**Issue by shimiaofeng** [hyperhq/hyper#27]

**Comment by shimiaofeng** [comment]
Logs : 
[HYPER INFO  0725 07:09:23 16679 xen.go] Xen Driver Load failed: failed to initialize xen context
[HYPER INFO  0725 07:09:23 16679 vm.go] Qemu Driver Loaded
[HYPER INFO  0725 07:09:23 16679 hyperd.go] The config file is 
[HYPER INFO  0725 07:09:23 16679 daemon.go] The config: kernel=/var/lib/hyper/kernel, initrd=/var/lib/hyper/hyper-initrd.img
[HYPER INFO  0725 07:09:23 16679 daemon.go] The config: bridge=, ip=
[HYPER INFO  0725 07:09:23 16679 daemon.go] The config: bios=/var/lib/hyper/bios-qboot.bin, cbfs=/var/lib/hyper/cbfs-qboot.rom
[HYPER INFO  0725 07:09:23 16679 network.go] bridge exist
[HYPER INFO  0725 07:09:23 16679 network.go] modprobe br_netfilter failed modprobe br_netfilter failed
[HYPER INFO  0725 07:09:23 16679 hyperd.go] Hyper daemon: 0.2.1 0
[HYPER INFO  0725 07:09:23 16679 job.go] +job acceptconnections()
[HYPER INFO  0725 07:09:23 16679 job.go] -job acceptconnections() OK
[HYPER INFO  0725 07:09:23 16679 hyperd.go] Daemon has completed initialization
[HYPER INFO  0725 07:09:23 16679 daemon.go] Get the pod item, pod is pod-pod-bjYnwuYLoe!
[HYPER INFO  0725 07:09:23 16679 daemon.go] Get the pod item, pod is pod-pod-jtXeHNBYRj!
[HYPER INFO  0725 07:09:23 16679 pod.go] leveldb: not found
[HYPER INFO  0725 07:09:23 16679 pod.go] Process the Containers section in POD SPEC
[HYPER INFO  0725 07:09:23 16679 create.go] The Repository is ubuntu, and the tag is latest
[HYPER INFO  0725 07:09:23 16679 job.go] +job serveapi(unix:///var/run/hyper.sock)
[HYPER INFO  0725 07:09:23 16679 server.go] Listening for HTTP on unix (/var/run/hyper.sock)
[HYPER INFO  0725 07:09:23 16679 server.go] Registering GET, /info
[HYPER INFO  0725 07:09:23 16679 server.go] Registering GET, /pod/info
[HYPER INFO  0725 07:09:23 16679 server.go] Registering GET, /version
[HYPER INFO  0725 07:09:23 16679 server.go] Registering GET, /list
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /pod/stop
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /vm/create
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /attach
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /container/create
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /image/create
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /pod/create
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /pod/start
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /pod/remove
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /tty/resize
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /pod/run
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /vm/kill
[HYPER INFO  0725 07:09:23 16679 server.go] Registering POST, /exec
[HYPER INFO  0725 07:09:23 16679 server.go] Registering OPTIONS, 
[HYPER INFO  0725 07:09:24 16679 create.go] The returned status code is 201!
[HYPER INFO  0725 07:09:24 16679 daemon.go] leveldb: not found for pod-bjYnwuYLoe
[HYPER INFO  0725 07:09:24 16679 pod.go] leveldb: not found
[HYPER INFO  0725 07:09:24 16679 pod.go] Process the Containers section in POD SPEC
[HYPER INFO  0725 07:09:24 16679 create.go] The Repository is ubuntu, and the tag is latest
[HYPER INFO  0725 07:09:24 16679 create.go] The returned status code is 201!
[HYPER INFO  0725 07:09:24 16679 daemon.go] leveldb: not found for pod-jtXeHNBYRj
[HYPER INFO  0725 07:09:54 16679 server.go] Calling POST /pod/run
[HYPER INFO  0725 07:09:54 16679 job.go] +job podRun({"id":"ubuntu-latest-2931021243","containers":[{"name":"ubuntu-latest-2931021243","image":"ubuntu:latest","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""})
[HYPER INFO  0725 07:09:54 16679 pod.go] {"id":"ubuntu-latest-2931021243","containers":[{"name":"ubuntu-latest-2931021243","image":"ubuntu:latest","command":[],"workdir":"/","entrypoint":[],"ports":[],"envs":[],"volumes":[],"files":[],"restartPolicy":"never"}],"resource":{"vcpu":1,"memory":128},"files":[],"volumes":[],"tty":true,"type":""}
[HYPER INFO  0725 07:09:54 16679 pod.go] The config: kernel=/var/lib/hyper/kernel, initrd=/var/lib/hyper/hyper-initrd.img
[HYPER INFO  0725 07:09:54 16679 pod.go] leveldb: not found
[HYPER INFO  0725 07:09:54 16679 pod.go] Process the Containers section in POD SPEC
[HYPER INFO  0725 07:09:54 16679 create.go] The Repository is ubuntu, and the tag is latest
[HYPER INFO  0725 07:09:54 16679 qemu_process.go] cmdline arguments: -machine pc-i440fx-2.0,accel=kvm,usb=off -global kvm-pit.lost_tick_policy=discard -cpu host -drive if=pflash,file=/var/lib/hyper/bios-qboot.bin,readonly=on -drive if=pflash,file=/var/lib/hyper/cbfs-qboot.rom,readonly=on -realtime mlock=off -no-user-config -nodefaults -no-hpet -rtc base=utc,driftfix=slew -no-reboot -display none -boot strict=on -m 128 -smp 1 -qmp unix:/var/run/hyper/vm-hvTPypPyGc/qmp.sock,server,nowait -serial unix:/var/run/hyper/vm-hvTPypPyGc/console.sock,server,nowait -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x2 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x3 -chardev socket,id=charch0,path=/var/run/hyper/vm-hvTPypPyGc/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch1,path=/var/run/hyper/vm-hvTPypPyGc/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -fsdev local,id=virtio9p,path=/var/run/hyper/vm-hvTPypPyGc/share_dir,security_model=none -device virtio-9p-pci,fsdev=virtio9p,mount_tag=share_dir
[HYPER INFO  0725 07:09:54 16679 qemu_process.go] qemu daemon pid 16792.
[HYPER INFO  0725 07:09:54 16679 qemu_process.go] starting daemon with pid: 16792
[HYPER INFO  0725 07:09:54 16679 init_comm.go] Wating for init messages...
[HYPER INFO  0725 07:09:54 16679 init_comm.go] trying to read 8 bytes
[HYPER INFO  0725 07:09:54 16679 tty.go] tty socket connected
[HYPER INFO  0725 07:09:54 16679 tty.go] tty: trying to read 12 bytes
[HYPER INFO  0725 07:09:54 16679 init_comm.go] connected to /var/run/hyper/vm-hvTPypPyGc/console.sock
[HYPER INFO  0725 07:09:54 16679 init_comm.go] connected /var/run/hyper/vm-hvTPypPyGc/console.sock as telnet mode.
[HYPER INFO  0725 07:09:54 16679 qmp_handler.go] connected to /var/run/hyper/vm-hvTPypPyGc/qmp.sock
[HYPER INFO  0725 07:09:54 16679 qmp_handler.go] begin qmp init...
[HYPER ERROR 0725 07:09:54 16679 init_comm.go] read init data failed
[HYPER ERROR 0725 07:09:54 16679 init_comm.go] read init message failed... read unix /var/run/hyper/vm-hvTPypPyGc/hyper.sock: connection reset by peer
[HYPER ERROR 0725 07:09:54 16679 qmp_handler.go] get qmp welcome failed: read unix /var/run/hyper/vm-hvTPypPyGc/qmp.sock: connection reset by peer
[HYPER INFO  0725 07:09:54 16679 hypervisor.go] main event loop got message 30(ERROR_INIT_FAIL)
[HYPER ERROR 0725 07:09:54 16679 vm_states.go] read init message failed... read unix /var/run/hyper/vm-hvTPypPyGc/hyper.sock: connection reset by peer
[HYPER ERROR 0725 07:09:54 16679 vm_states.go] Shutting down because of an exception: Fail during init environment
[HYPER INFO  0725 07:09:54 16679 context.go] VM vm-hvTPypPyGc: state change from  to 'DESTROYING'
[HYPER ERROR 0725 07:09:54 16679 qmp_handler.go] QMP initialize failed
[HYPER INFO  0725 07:09:54 16679 hypervisor.go] main event loop got message 30(ERROR_INIT_FAIL)
[HYPER WARN  0725 07:09:54 16679 vm_states.go] got event during vm cleaning up
[HYPER INFO  0725 07:09:54 16679 tty.go] Input byte chan closed, close the output string chan
[HYPER INFO  0725 07:09:54 16679 init_comm.go] console output end
[HYPER ERROR 0725 07:09:54 16679 tty.go] read tty data failed
[HYPER INFO  0725 07:09:54 16679 tty.go] tty socket closed, quit the reading goroutine read unix /var/run/hyper/vm-hvTPypPyGc/tty.sock: connection reset by peer
[HYPER INFO  0725 07:09:54 16679 hypervisor.go] main event loop got message 32(ERROR_INTERRUPTED)
[HYPER INFO  0725 07:09:54 16679 vm_states.go] Connection interrupted while destroying
[HYPER INFO  0725 07:09:54 16679 tty.go] tty chan closed, quit sent goroutine
[HYPER INFO  0725 07:09:54 16679 create.go] The returned status code is 201!
[HYPER INFO  0725 07:09:54 16679 container.go] ready to get the container(30e342681b5842bc790f8cb6b1f38562c576d9e074cc7da79f97d869959d78bf) info
[HYPER INFO  0725 07:09:54 16679 pod.go] Parsing envs for container 0: 0 Evs
[HYPER INFO  0725 07:09:54 16679 pod.go] The fs type is ext4
[HYPER INFO  0725 07:09:54 16679 pod.go] WorkingDir is 
[HYPER INFO  0725 07:09:54 16679 pod.go] Image is /dev/mapper/docker-253:0-2490566-30e342681b5842bc790f8cb6b1f38562c576d9e074cc7da79f97d869959d78bf
[HYPER INFO  0725 07:09:54 16679 pod.go] Container Info is 
&{30e342681b5842bc790f8cb6b1f38562c576d9e074cc7da79f97d869959d78bf /rootfs /dev/mapper/docker-253:0-2490566-30e342681b5842bc790f8cb6b1f38562c576d9e074cc7da79f97d869959d78bf ext4  [] [/bin/bash] map[]}
[HYPER INFO  0725 07:09:54 16679 pod.go] container 0 created 30e342681b5842bc790f8cb6b1f38562c576d9e074cc7da79f97d869959d78bf, workdir , env: map[]
POD id is pod-GMkKPksKAf
[HYPER INFO  0725 07:09:54 16679 hypervisor.go] main event loop got message 20(COMMAND_RUN_POD)
[HYPER WARN  0725 07:09:54 16679 vm_states.go] got event during vm cleaning up
[HYPER INFO  0725 07:09:54 16679 pod.go] Get the response from QEMU, VM id is vm-hvTPypPyGc!
[HYPER INFO  0725 07:09:54 16679 hypervisor.go] main event loop got message 23(COMMAND_SHUTDOWN)
[HYPER WARN  0725 07:09:54 16679 vm_states.go] got event during vm cleaning up
[HYPER INFO  0725 07:10:04 16679 hypervisor.go] main event loop got message 3(EVENT_VM_TIMEOUT)
[HYPER INFO  0725 07:10:04 16679 vm_states.go] Device removing timeout
[HYPER INFO  0725 07:10:04 16679 qemu_process.go] quit watch dog.

**Comment by gnawux** [comment]
hi @shimiaofeng ,

As you did not provide any further info, I can not judge what's the matter.

If you do not have ubuntu image in your host, it may be downloading the image from docker hub. In the next release, hyper will provide friendly message about on going jobs. If you think you met other problems, you'd better paste logs here.

Thank you.

**Comment by gnawux** [comment]
hi @shimiaofeng 

I read the log message, looks like the qemu in your machine did not start properly, could you give the version of your qemu. And if you built qemu by yourself, could you give your qemu configuration?

Thank you!

**Comment by shimiaofeng** [comment]
The ubuntu images has already download and exist in host. I can run hyper pull command successfully.
host os is centos 6.6 and update kernel to 3.10.18
I download the qemu2.0.0 and execute ./configure default and then make

**Comment by shimiaofeng** [comment]
@gnawux, should I edit the configure file when build qemu?

**Comment by gnawux** [comment]
hi @shimiaofeng ,

No, default qemu should works well, but I suggest you check whether the virtfs is enabled (`--enable-virtfs`). Actually we had tested hyper with self built qemu on CentOS, and did not specify any special flags.

And you can have more detailed daemon log with [`hyperd -v=1`](https://docs.hyper.sh/trouble_shooting/index.html)

**Comment by shimiaofeng** [comment]
@gnawux 
I build qume2.0 with virtfs enabled and now work well. Thanks.
By the way , bring your own kernel means I could build any other linux kernels ? have docs  to follow this work?

**Comment by gnawux** [comment]
@shimiaofeng , yes, you can find the configuration in [doc](https://docs.hyper.sh/reference/configuration.html)  and [this FAQ page](https://docs.hyper.sh/trouble_shooting/general.html). 

Thank you

**Comment by shimiaofeng** [comment]
@gnawux 
does any commands exsit that could copy files between host and hyper VMs,like docker cp ?

**Comment by gnawux** [comment]
use

    hyper list container

**Comment by gnawux** [comment]
use 

    hyper list container 

you can get all the container IDs inside pod. then you can use  `docker cp` with the container. to avoid conflict with docker. hyper share the on disk container fs with docker.

**Comment by shimiaofeng** [comment]
docker cp  copy file from contaner to host successfuly. But  with cp command to copy file from host to conainer ,I could not find the file inside ?

**Comment by gao-feng** [comment]
@shimiaofeng hi, the man page of docker cp says `docker-cp - Copy files or folders from a container's PATH to a HOSTDIR or to STDOUT.`.
