### ISSUE TITLE
certificate issues with various commands (signed by unknown authority)

### ISSUE THREAD

**Issue by jdc0589** [hyperhq/hyper#275]
All of the `fip` commands blow up with the following for me:

```bash
~
▶ hyper fip allocate 1
An error occurred trying to connect: Post https://us-west-1.hyper.sh:443/v1.23/fips/allocate?count=1: x509: certificate signed by unknown authority
```

I was able to pull images, make a data volume, and run a container successfully though.

**Comment by jdc0589** [comment]
Looks like this is an inconsistent issue? same just happened after a `hyper ps`, but is now working correctly for `fip` commands

**Comment by gnawux** [comment]
@jdc0589 

Hyper client itself is a docker client with API signature, thus it is affected by some docker environment. With docker private ca configured, I've tried this

```
➜  docker git:(master) ✗ hyper images
An error occurred trying to connect: Get https://us-west-1.hyper.sh:443/v1.23/images/json: x509: certificate signed by unknown authority
➜  docker git:(master) ✗ DOCKER_TLS_VERIFY="" hyper images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
ubuntu                            latest              a1e4ed2ac65b        46 hours ago        187.9 MB
alpine                            latest              d7a513a663c1        5 days ago          4.794 MB
nginx                             latest              af4b3d7d5401        4 weeks ago         190.5 MB
```

We will update a new client to eliminate this problem, and you can use this (DOCKER_TLS_VERIFY="" hyper) as a work around.

PS: This is a bit confusing. The hyperhq/hyper rep is the backend container engine of  hyper.sh, while the https://github.com/hyperhq/hypercli is the repo for command line tool.

**Comment by jdc0589** [comment]
@gnawux my bad, I didn't even think to look for a CLI. I'll update mine in the morning to make sure I have the latest. If its still an issue, I'll reopen this in the right tracker.

thanks.

**Comment by gnawux** [comment]
@jdc0589 It's our problem. Sorry for the confusing. Anyway, the same team replies the Issues.
