### ISSUE TITLE
Hyper can work with KVM??

### ISSUE THREAD

**Issue by jefby** [hyperhq/hyper#29]
Hi, can hyper work with KVM now?? I just have a kernel image with KVM, not xen.

**Comment by carmark** [comment]
Hi @jefby ,

Yeah, `hyper` can wok with KVM.  You can configure your kernel and initrd in the config file.

Regards,

**Comment by jefby** [comment]
@carmark Hi , i compile the hyper code and run hyperd ,it can't work, why ? and how to set the config ??Thanks very much.

```
# ./hyperd
[HYPER INFO  0802 15:36:21 04972 xen.go] Xen Driver Load failed: failed to initialize xen context
[HYPER INFO  0802 15:36:21 04972 vm.go] Qemu Driver Loaded
[HYPER INFO  0802 15:36:21 04972 hyperd.go] The config file is
[HYPER ERROR 0802 15:36:21 04972 daemon.go] Read config file (/etc/hyper/config) failed, open /etc/hyper/config: no such file or directory
[HYPER ERROR 0802 15:36:21 04972 hyperd.go] The hyperd create failed, open /etc/hyper/config: no such file or directory
```

**Comment by carmark** [comment]
@jefby 

You can compile the hyperd without xen support via the following command:
```
 ./autogen.sh
 ./configure --without-xen
 make
```

And then you can specify that config file with `--config=xxx` option, you may refer this [link](https://docs.hyper.sh/reference/configuration.html) if you want more details.

Regards,

**Comment by Termina1** [comment]
And what about [xhyve](https://github.com/mist64/xhyve)?

**Comment by carmark** [comment]
@Termina1 

Now, we have no plan to implement the `hyper` with `xhyve`, but any contribution is welcome.
