### ISSUE TITLE
cant live migrate hyper because of virtfs

### ISSUE THREAD

**Issue by YaoZengzeng** [hyperhq/hyper#32]
Hi,@carmark I want to live miagrate hyper VM,but it seems impossible.When I use qemu-system-x86_64 monitor to savevm and then loadvm,I cant go into the shared folder any more.It seems that the VM thinks the virtfs is still mounted,but it's not in fact.So I want to know if I can live migrate hyper with virtfs?Thanks!

**Comment by carmark** [comment]
Hello @YaoZengzeng ,

Currently, you can not do live migration with virtfs.

Regards,
