### ISSUE TITLE
No such image: ubuntu

### ISSUE THREAD

**Issue by feiskyer** [hyperhq/hyper#47]
[HYPER ERROR 0820 01:10:^@23 42047 server.go] [:132] HTTP Error: statusCode=404 No such image: ubuntu (tag: latest)
[HYPER ERROR 0820 01:10:^@33 42047 tags.go] [:156] could not find image: no such id: ubuntu
[HYPER ERROR 0820 01:10:^@33 42047 create.go] [:61] could not find image: no such id: ubuntu
[HYPER ERROR 0820 01:10:^@33 42047 pod.go] [:167] No such image: ubuntu (tag: latest)
[HYPER ERROR 0820 01:10:^@33 42047 server.go] [:884] Handler for POST /pod/create returned error: No such image: ubuntu (tag: latest)

**Comment by jstoja** [comment]
@feiskyer What command did you run to have this message?

**Comment by carmark** [comment]
@feiskyer @jstoja 

This issue should be encountered while creating a new pod, but the image is not exist.   The patch https://github.com/hyperhq/hyper/pull/53 fix this.
