### ISSUE TITLE
Error message disappear when message length more than 150 

### ISSUE THREAD

**Issue by gao-feng** [hyperhq/hyper#56]
https://github.com/hyperhq/hyper/blob/master/client/utils.go#L101

such as this error message.

./hyper ERROR: Conflict. The name "ubuntu-interface2" is already in use by container 6ff8191192c6. You have to delete (or rename) that container to be able to reuse that name.

**Comment by carmark** [comment]
fixed by https://github.com/hyperhq/hyper/pull/57
