### ISSUE TITLE
we need keep consistent user experience for hyper run and docker run

### ISSUE THREAD

**Issue by xiaods** [hyperhq/hyper#62]
hyper is difference than docker. but there is a defacto integration with docker images. then here is broken user experience.

case:
hyper run ubuntu:latest
the cli will broken when ubuntu images is not download and cached in local

but if you run blow cmd: 
```
docker run httpd:latest
Unable to find image 'httpd:latest' locally
```
the cli will continue download images and run the ubuntu step by step.

So i proposal apply this feature to improve user experience.

My ENV:
```
$ sw_vers 
ProductName:    Mac OS X
ProductVersion: 10.10.5
BuildVersion:   14F27

$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

$ hyper version
The hyper version is 0.3
```

**Comment by gnawux** [comment]
@xiaods I agree with your point. @carmark will take the responsibility of the command line compatibility.

Thank you

**Comment by carmark** [comment]
This have been fixed by https://github.com/hyperhq/hyper/commit/d157ab756960f3e032896757c9822e7ca0bdba44, would @xiaods like to try that commit or wait the latest version(hyper#0.4.0)?

**Comment by xiaods** [comment]
@carmark done.
