### ISSUE TITLE
the introduction docker pull is very confuse for hyper starter

### ISSUE THREAD

**Issue by xiaods** [hyperhq/hyper#63]
I know the docker pull concepts in hyper introduction, it mean hyper can use docker pulled images at once. but for cross platform, the hyper is agnostic docker alike container engine, not docker. so we don't need introduce duplicate docker cmd in hyper introduction.
so we need change the introduction in start page.

docker pull ubuntu:latest change to hyper pull ubuntu:latest
hyper run ubuntu:latest

done.

**Comment by gnawux** [comment]
@xiaods It has already been implemented in `master` branch. Uou will be able to use `hyper pull` next week, or build from source of `master` branch. 

Thank you.

**Comment by xiaods** [comment]
@gnawux my point is remove "docker pull", only introduce "hyper pull". hyper is hyper way, don't need docker even it support docker cli.
