### ISSUE TITLE
Unable to launch Docker image "danielbodart/crazyfast.build"

### ISSUE THREAD

**Issue by danielbodart** [hyperhq/hyper#64]
Dockerfile: https://github.com/bodar/crazyfast.build/blob/master/Dockerfile

Build image: https://hub.docker.com/r/danielbodart/crazyfast.build/

Tried running either:

sudo hyper run danielbodart/crazyfast.build

or 

create / run / attach

Logs:

[HYPER INFO  0915 07:37:41 02828 server.go] Calling POST /pod/start
[HYPER INFO  0915 07:37:41 02828 job.go] +job podStart(pod-TBbcHKIYuU, )
[HYPER INFO  0915 07:37:41 02828 pod.go] pod:%s, vm:%spod-TBbcHKIYuU
[HYPER INFO  0915 07:37:41 02828 vm_states.go] got spec, prepare devices
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] got new session during initializing
[HYPER INFO  0915 07:37:41 02828 init_comm.go] Wating for init messages...
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] begin qmp init...
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] got qmp welcome, now sending command qmp_capabilities
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] waiting for response
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] got for response
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] QMP connection initialized
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] QMP initialzed, go into main QMP loop
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] Begin receive QMP message
[HYPER INFO  0915 07:37:41 02828 qmp_handler.go] session finished, buffer size 1
[HYPER INFO  0915 07:37:42 02828 init_comm.go] Get init ready message
[HYPER INFO  0915 07:37:42 02828 vm_states.go] begin to wait vm commands
[HYPER INFO  0915 07:37:42 02828 vm_states.go] pod start success 
[HYPER INFO  0915 07:37:42 02828 job.go] -job podStart(pod-TBbcHKIYuU, ) OK
[HYPER INFO  0915 07:37:42 02828 qmp_handler.go] Shutdown, quit QMP receiver
[HYPER INFO  0915 07:37:42 02828 qmp_handler.go] got QMP shutdown event, quit...
[HYPER INFO  0915 07:37:42 02828 vm_states.go] Got VM shutdown event while terminating, go to cleaning up
[HYPER ERROR 0915 07:37:42 02828 tty.go] read tty data failed
[HYPER ERROR 0915 07:37:42 02828 init_comm.go] read init data failed
[HYPER INFO  0915 07:37:42 02828 vm_states.go] resources reclaimed, quit...
[HYPER INFO  0915 07:37:42 02828 init_comm.go] vm channel closed, quit

**Comment by carmark** [comment]
@danielbodart 

could you please provide more information? such as `hyper info` and host os information.

**Comment by gnawux** [comment]
@carmark os is linux, and hypervisor is qemu/kvm, check the slack discussion :)

**Comment by danielbodart** [comment]
sudo hyper info
Containers: 6
PODs: 3
Total Memory: 32896704 KB
Operating System: Ubuntu 15.04

uname -a
Linux desktop 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

sudo service hyperd status
● hyperd.service - hyperd
   Loaded: loaded (/lib/systemd/system/hyperd.service; disabled; vendor preset: enabled)
   Active: active (running) since Tue 2015-09-15 06:54:53 BST; 1h 33min ago
     Docs: http://docs.hyper.sh
 Main PID: 2828 (hyperd)
   CGroup: /system.slice/hyperd.service
           ├─2828 /usr/local/bin/hyperd
           └─5376 qemu-system-x86_64 -machine pc-i440fx-2.0,accel=kvm,usb=off -global kvm-pit.lost_tick_policy=discard -cpu host -drive if...

Sep 15 07:56:50 desktop hyperd[2828]: [HYPER INFO  0915 07:56:
Sep 15 07:56:50 desktop hyperd[2828]: [HYPER INFO  0915 07:56:
Sep 15 07:56:50 desktop hyperd[2828]: [HYPER INFO  0915 07:56:
Sep 15 07:56:50 desktop hyperd[2828]: [HYPER INFO  0915 07:56:
Sep 15 07:58:36 desktop hyperd[2828]: [HYPER INFO  0915 07:58:
Sep 15 07:58:36 desktop hyperd[2828]: [HYPER INFO  0915 07:58:
Sep 15 07:58:36 desktop hyperd[2828]: 2015/09/15 07:58:36 http: response.WriteHeader on hijacked connection
Sep 15 08:26:45 desktop hyperd[2828]: [HYPER INFO  0915 08:26:
Sep 15 08:26:45 desktop hyperd[2828]: [HYPER INFO  0915 08:26:
Sep 15 08:26:45 desktop hyperd[2828]: [HYPER INFO  0915 08:26:

**Comment by carmark** [comment]
@danielbodart  Thanks, I will reproduce this on my local environment and fix it ASAP.

**Comment by danielbodart** [comment]
Thanks a lot for the fast response!

**Comment by carmark** [comment]
Hello @danielbodart ,

I did reproduce this issue, and this bug should be caused by DNS issue.  Since there is no DNS setting by the current release(next release will add default DNS setting), and it will be failed when you want to clone the code from github.

I have a simple workaround, you can create a pod file, like this one:

```
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# cat examples/crazyfast.pod
{
	"id": "test-container-create-crazyfast",
	"containers" : [{
	    "name": "crazyfast-sh",
	    "image": "danielbodart/crazyfast.build:latest",
		"files":  [{
            "path": "/etc/",
            "filename": "resolv.conf",
            "perm": "0755"
        }]
	}],
	"resource": {
	    "vcpu": 1,
	    "memory": 512
	},
    "files": [{
        "name": "resolv.conf",
        "encoding": "raw",
        "content": "nameserver 8.8.8.8"
    }],
	"volumes": [],
	"tty": true
}
```

That container's name must be unique, or you can not create the pod successfully.  I used this pod file and attach that created pod, you will find that the cmd clone the code from github.  However, there are some errors, I am not sure what it is, such as:

```
root@ubuntu:/home/lei/src/github.com/hyperhq/hyper# ./hyper attach pod-VQMBfJsrpM
# clone code from github
error: unable to open object pack directory: /crazyfast.build/totallylazy/.git/objects/pack: Invalid argument
.
.
.
error: unable to open object pack directory: /crazyfast.build/totallylazy/.git/objects/pack: Invalid argument
error: unable to open object pack directory: /crazyfast.build/totallylazy/.git/objects/pack: Invalid argument
error: unable to open object pack directory: /crazyfast.build/totallylazy/.git/objects/pack: Invalid argument
error: unable to open object pack directory: /crazyfast.build/totallylazy/.git/objects/pack: Invalid argument
Resolving deltas: 100% (14856/14856), done.
fatal: Unable to create temporary file '/crazyfast.build/totallylazy/.git/objects/pack/tmp_idx_XXXXXX': Invalid argument
fatal: index-pack failed
ls: cannot access */: No such file or directory
./run: line 8: ./jcompilo.sh: No such file or directory
```

I will check your dockerfile and try to find out it.

Thanks,

**Comment by danielbodart** [comment]
Okay so adding the the resolve config fixes DNS lookups. 

However I think the default file system is not writeable by git.

If you run the standard ubuntu:latest (with the resolve pod file) image in hyper and then attach to the console:

1. apt-get update
2. apt-get install git
3. git checkout https://github.com/hyperhq/hyper.git

You will see the same messages as my image.

**Comment by carmark** [comment]
Thanks for your report, I will check it again.

Regards,
-Lei

**Comment by danielbodart** [comment]
Okay investigating further this seams to be a problem with certain virtual file systems in qemu, is it possible to change the default virtual file system used by hyper? What is the default (qcow2)?

**Comment by gnawux** [comment]
For images, hyper support `devicemapper`(as raw device), `aufs` and `overlayfs` (though `virtfs`), for volumes, `qcow2`, `raw`(as raw device), and `vfs`(though `virtfs`) are supported.

@carmark please check the fs problem

**Comment by danielbodart** [comment]
Okay so if I create a "raw" volume and then run git in that folder it works fine.

So I'd like to try changing the default storage driver from aufs to overlayfs and if that works. Any suggestions how I do that?

**Comment by carmark** [comment]
@danielbodart 

For now, the priority is defined in `lib/docker/daemon/graphdriver`, and it is 

```
Priority = []string {
    "aufs",
    "overlay",
    "devicemapper",
    "vbox",
    "vfs",
}
```

You may need to modify that above code and rebuild hyper if you want to use `overlay` as the storage backend.

**Comment by gnawux** [comment]
@carmark we'd better make it an configurable parameter

**Comment by carmark** [comment]
@gnawux It is a good choice to make it configurable, I will do that fix.

**Comment by laijs** [comment]
#92

**Comment by gnawux** [comment]
#92 fixed this
