### ISSUE TITLE
Use some CI to gate pull requests

### ISSUE THREAD

**Issue by achanda** [hyperhq/hyper#9]
Run automated tests before a human takes a look at a PR

**Comment by gnawux** [comment]
Yes, will do soon, and we also need more test cases. Thanks @achanda

**Comment by henrysher** [comment]
+1, better to prepare a docker image (with all dependencies) to build, test and deliver the binaries, hyper & hyperd .

**Comment by gnawux** [comment]
#85 added travis CI
