### ISSUE TITLE
Hyper pods don't use the hosts dns

### ISSUE THREAD

**Issue by danielbodart** [hyperhq/hyper#90]
Currently the only way to get pods to be able to resolve outside DNS names is to add the following to the pod config:

```
{
   ...
    "containers" : [{
      ....
        "files":  [{
            "path": "/etc/",
            "filename": "resolv.conf",
            "perm": "0755"
        }]
    }],
    "files": [{
        "name": "resolv.conf",
        "encoding": "raw",
        "content": "nameserver 8.8.8.8 " <- Google DNS etc
    }],
}
```

NB: I've removed (...) stuff for readability.

It would be good if hyperd by default used the host dns and maybe supported the same options as the docker daemon where you can set the dns and search prefix

**Comment by gnawux** [comment]
@carmark the volume mapping should allow mapping both file and dir, please fix it
