### ISSUE TITLE
Add logging support [enhancement]

### ISSUE THREAD

**Issue by danielbodart** [hyperhq/hyper#94]
This is a feature request, it would be great if hyper supported logging much like docker logging:

https://docs.docker.com/reference/logging/overview/

Ideally I'd like to be able:

1. See logs like 'docker logs ...'
2. Plug in my own logger driver 'docker run --log-driver=...'

As GO supports structural typing maybe the docker logging drivers could be supported without actually adding the docker dependency back in or having to implement the drivers all over again!

https://github.com/docker/docker/blob/master/daemon/logger/logger.go

Or maybe we really should just go the more unix way and just make sure we can pipe from the TTY console.

**Comment by gnawux** [comment]
the feature was implemented by #112
