### ISSUE TITLE
hyper pull always returns exit code 0 even if it errors in some way

### ISSUE THREAD

**Issue by danielbodart** [hyperhq/hyper#99]
If you run 

```
hyper pull someinvalidimagename
```

It will return 0

**Comment by danielbodart** [comment]
Wow, that was fast.

I assume this will fix it for all cases?

I.e if the hyperd is not started or if I run a different command?

**Comment by gnawux** [comment]
@danielbodart yes, the original code does not return non-zero value for the error of all commands execution. Sorry for the inconvenient.
